name: 'Zip Files'
description: 'Zipping files and folders'
inputs:
  path:
    description: "Files or folders to zip"
    required: true
  name:
    description: "Zip file name"
    required: true
outputs:
  output:
    description: "Zip file path"
runs:
  using: "node20"
  main: "dist/index.js"
